# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QPVthrBHxgn7ze8Lbxx5z9ZLLAB01inC
"""

pip install tweepy

pip install configparser

pip install pandas

import tweepy 
import configparser
import pandas as pd
#read config parser

config = configparser.ConfigParser()
config.read('config.ini')
api_key = config['twitter']['api_key']
api_key_secret = config['twitter']['api_key_secret']

access_token = config['twitter']['access_token']
access_token_secret = config['twitter']['access_token_secret']

#authentication
auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

public_tweets = api.home_timeline()

columns = ['Time','User','Tweet']
data = []

for tweet in public_tweets:
  data.append([tweet.created_at,tweet.user.screen_name,tweet.text])

df = pd.DataFrame(data, columns=columns)
print(df)

df.to_csv('tweets.csv')